version: '3.8'
services:
  backend:
    build: .
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/grocerydb
      - JWT_SECRET=devsecret
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
